// Vitamin Browser - Poison Data
// All features free and open source

// Frequency options - user selects how aggressive poisoning should be
const frequencies = {
  low: {
    name: 'Low',
    label: 'Chill',
    minDelay: 45000,
    maxDelay: 90000,
    description: 'Gentle poisoning every 45-90 seconds. Safe for all sites.',
    warning: null
  },
  medium: {
    name: 'Medium',
    label: 'Standard',
    minDelay: 20000,
    maxDelay: 45000,
    description: 'Balanced poisoning every 20-45 seconds.',
    warning: null
  },
  high: {
    name: 'High',
    label: 'Aggressive',
    minDelay: 10000,
    maxDelay: 25000,
    description: 'Fast poisoning every 10-25 seconds.',
    warning: 'Some sites may rate-limit or temporarily block you.'
  },
  max: {
    name: 'Maximum',
    label: 'Overdose',
    minDelay: 5000,
    maxDelay: 15000,
    description: 'Maximum poisoning every 5-15 seconds.',
    warning: 'High risk of rate-limiting or bans from some websites. Use with caution.'
  }
};

// Generic search terms
const genericSearchTerms = [
  // Shopping
  'best hiking boots 2024', 'cheap blender reviews', 'organic dog food',
  'winter jacket sale', 'running shoes for flat feet', 'standing desk amazon',
  'air fryer recipes', 'yoga mat thick', 'noise canceling headphones budget',
  'ergonomic office chair', 'water bottle insulated', 'backpack laptop',
  'wireless mouse reviews', 'desk lamp led', 'coffee maker best',
  'mechanical keyboard switches', 'ultrawide monitor gaming', '4k webcam streaming',
  'nvme ssd benchmark', 'thunderbolt dock reviews', 'mesh wifi system',
  'portable power bank', 'smartphone comparison', 'tablet for drawing',
  'gaming chair comfort', 'led strip lights', 'usb c hub',
  'smartwatch fitness tracker', 'laptop cooling pad', 'headphones wireless bluetooth',
  'bluetooth speaker portable', 'external hard drive', 'memory card sd',
  'charging cable fast', 'phone case clear', 'screen protector tempered glass',
  'wireless earbuds cheap', 'smart home hub', 'robot vacuum cleaner',
  'security camera outdoor', 'smart doorbell', 'led light strip rgb',
  'gaming mouse dpi', 'keyboard wireless mechanical', 'monitor mount adjustable',
  'printer wireless', 'ink cartridge replacement', 'scanner document',
  'router wifi 6', 'modem wifi combo', 'network switch gigabit',
  'ups battery backup', 'surge protector', 'cable management',
  'desk accessories organizer', 'office supplies', 'notebook planner',
  'pens gel ink', 'sticky notes', 'tape dispenser',
  'paper clips', 'stapler', 'hole punch',
  'whiteboard markers', 'erasers', 'rulers',
  'highlighters', 'markers', 'crayons',
  'paint brushes', 'canvas', 'easel',
  'glue stick', 'scissors', 'paper cutter',
  'filing cabinet', 'shredder', 'label maker',
  'desk calendar', 'wall clock', 'picture frame',
  'plant indoor', 'lamp table', 'rug area',
  'curtains', 'blinds', 'window film',
  'door mat', 'wall art', 'decorative vase',
  'throw pillow', 'blanket cozy', 'bed sheets',
  'towels', 'bath mat', 'shower curtain',
  'toilet paper', 'soap', 'shampoo',
  'toothbrush', 'toothpaste', 'mouthwash',
  'deodorant', 'perfume', 'cologne',
  'lotion', 'sunscreen', 'makeup remover',
  'face mask', 'eye cream', 'serum vitamin c',
  'cleanser', 'toner', 'moisturizer',
  'foundation', 'concealer', 'powder setting',
  'eyeshadow', 'mascara', 'eyeliner',
  'lipstick', 'lip gloss', 'lip balm',
  'nail polish', 'nail file', 'cuticle oil',
  'hairbrush', 'hair dryer', 'straightener',
  'curling iron', 'hair ties', 'hair clips',
  'shaving cream', 'razor blades', 'aftershave',
  'baby wipes', 'diapers', 'baby food',
  'pet food', 'cat litter', 'dog treats',
  'bird seed', 'fish food', 'hamster wheel',
  'plant fertilizer', 'pest control', 'weed killer',
  'lawn mower', 'hedge trimmer', 'leaf blower',
  'snow blower', 'pressure washer', 'generator',
  'power drill', 'screwdriver set', 'hammer',
  'nails', 'screws', 'bolts',
  'wrench set', 'pliers', 'tape measure',
  'level', 'stud finder', 'caulking gun',
  'paint roller', 'brush set', 'drop cloth',
  'sandpaper', 'wood stain', 'varnish',
  'glue wood', 'nails finishing', 'screws drywall',
  'drywall tape', 'joint compound', 'texture spray',
  'insulation', 'weather stripping', 'door sweep',
  'window seal', 'caulk', 'expanding foam',
  'duct tape', 'electrical tape', 'masking tape',
  'packing tape', 'bubble wrap', 'moving boxes',
  'zip ties', 'cable ties', 'bungee cords',
  'rope', 'chain', 'padlock',
  'safe', 'fire extinguisher', 'carbon monoxide detector',
  'smoke detector', 'first aid kit', 'flashlight',
  'batteries', 'candles', 'matches',
  'lighter', 'camping gear', 'tent',
  'sleeping bag', 'camping stove', 'cooler',
  'backpack hiking', 'water bottle', 'headlamp',
  'compass', 'map', 'binoculars',
  'fishing rod', 'fishing reel', 'fishing line',
  'fishing hooks', 'lures', 'bait',
  'hunting gear', 'gun safe', 'ammunition',
  'archery', 'compound bow', 'arrows',
  'ski equipment', 'snowboard', 'snowboard boots',
  'ski boots', 'ski poles', 'helmet',
  'bike helmet', 'bike lock', 'bike lights',
  'bike rack', 'pump', 'tire patch kit',
  'car jack', 'tire gauge', 'jump starter',
  'oil change', 'air filter', 'spark plugs',
  'brake pads', 'wiper blades', 'antifreeze',
  'coolant', 'transmission fluid', 'power steering fluid',
  'brake fluid', 'windshield washer fluid', 'tire shine',
  'car wax', 'car wash', 'vacuum',
  'air freshener', 'floor mats', 'seat covers',
  'steering wheel cover', 'phone mount', 'dash cam',
  'gps', 'car charger', 'bluetooth adapter',
  'fm transmitter', 'obd2 scanner', 'tire pressure monitor',
  'engine cleaner', 'degreaser', 'rust remover',
  'touch up paint', 'dent repair', 'headlight restoration',
  'car cover', 'trailer hitch', 'bike rack hitch',
  'roof rack', 'cargo box', 'kayak rack',
  'ski rack', 'surfboard rack', 'ladder',
  'toolbox', 'tool belt', 'work boots',
  'safety glasses', 'ear protection', 'gloves work',
  'knee pads', 'hard hat', 'respirator mask',
  'dust mask', 'ear plugs', 'hearing protection',
  'safety vest', 'first aid supplies', 'bandages',
  'antiseptic', 'pain relievers', 'allergy medicine',
  'cold medicine', 'flu medicine', 'vitamins',
  'supplements', 'protein powder', 'meal replacement',
  'coffee maker', 'espresso machine', 'blender',
  'food processor', 'mixer', 'toaster',
  'microwave', 'oven', 'stove',
  'refrigerator', 'dishwasher', 'washer',
  'dryer', 'vacuum cleaner', 'iron',
  'steam cleaner', 'carpet cleaner', 'window cleaner',
  'laundry detergent', 'fabric softener', 'bleach',
  'stain remover', 'dry cleaning', 'shoe cleaner',
  'leather conditioner', 'furniture polish', 'glass cleaner',
  'disinfectant', 'air purifier', 'humidifier',
  'dehumidifier', 'fan', 'space heater',
  'air conditioner', 'heater', 'thermostat',
  'smart outlet', 'smart switch', 'smart bulb',
  'led bulb', 'fluorescent bulb', 'incandescent bulb',
  'light fixture', 'ceiling fan', 'chandelier',
  'sconce', 'lamp shade', 'dimmer switch',
  'electrical outlet', 'switch plate', 'junction box',
  'circuit breaker', 'electrical panel', 'wire',
  'romex', 'conduit', 'electrical tape',
  'wire nuts', 'electrical box', 'gfci outlet',
  'afci breaker', 'arc fault breaker', 'gfci breaker',
  'electrical meter', 'service panel', 'main breaker',
  'sub panel', 'electrical conduit', 'flexible conduit',
  'liquid pliers', 'pipe wrench', 'basin wrench',
  'toilet plunger', 'toilet auger', 'drain snake',
  'garbage disposal', 'faucet', 'shower head',
  'tub spout', 'valve', 'shutoff valve',
  'ball valve', 'gate valve', 'check valve',
  'pressure valve', 'relief valve', 'thermostatic valve',
  'mixing valve', 'diverter valve', 'shower valve',
  'toilet seat', 'toilet bowl', 'toilet tank',
  'bidet', 'urinal', 'sink faucet',
  'kitchen faucet', 'bar faucet', 'laundry faucet',
  'hose bibb', 'outdoor faucet', 'sillcock',
  'garden hose', 'hose nozzle', 'hose reel',
  'hose connector', 'hose repair', 'hose end',
  'sprinkler', 'irrigation', 'drip system',
  'soaker hose', 'timer', 'controller',
  'rain sensor', 'moisture sensor', 'flow sensor',
  'pressure sensor', 'temperature sensor', 'humidity sensor',
  'motion sensor', 'light sensor', 'door sensor',
  'window sensor', 'glass break sensor', 'smoke detector sensor',
  'co detector', 'radon detector', 'air quality sensor',
  'water leak sensor', 'flood sensor', 'freeze sensor',
  'heat sensor', 'uv sensor', 'wind sensor',
  'rain gauge', 'weather station', 'barometer',
  'anemometer', 'wind vane', 'pyranometer',
  'lux meter', 'sound level meter', 'vibration meter',
  'multimeter', 'oscilloscope', 'function generator',
  'power supply', 'signal generator', 'frequency counter',
  'logic analyzer', 'spectrum analyzer', 'network analyzer',
  'rf generator', 'rf analyzer', 'protocol analyzer',
  'data logger', 'chart recorder', 'strip chart recorder',
  'temperature controller', 'pid controller', 'plc',
  'scada', 'hmi', 'motor starter',
  'contactors', 'relays', 'solenoids',
  'transformers', 'inductors', 'capacitors',
  'resistors', 'diodes', 'transistors',
  'integrated circuits', 'microcontrollers', 'microprocessors',
  'fpgas', 'cplds', 'memory modules',
  'storage devices', 'hard drives', 'solid state drives',
  'optical drives', 'tape drives', 'network storage',
  'raid controller', 'network switch', 'router',
  'firewall', 'vpn', 'proxy server',
  'load balancer', 'content filter', 'web server',
  'application server', 'database server', 'mail server',
  'dns server', 'dhcp server', 'ntp server',
  'radius server', 'ldap server', 'terminal server',
  'remote access', 'virtual desktop', 'cloud computing',
  'virtualization', 'containers', 'kubernetes',
  'docker', 'openshift', 'mesos',
  'swarm', 'nomad', 'consul',
  'vault', 'terraform', 'ansible',
  'puppet', 'chef', 'saltstack',
  'jenkins', 'gitlab ci', 'github actions',
  'circleci', 'travisci', 'bamboo',
  'teamcity', 'gocd', 'drone',
  'concourse', 'buildkite', 'azure devops',
  'bitbucket pipelines', 'codepipeline', 'spinnaker',
  'argocd', 'flux', 'helm',
  'kustomize', 'istio', 'linkerd',
  'consul connect', 'ambassador', 'traefik',
  'nginx', 'apache', 'iis',
  'tomcat', 'jetty', 'glassfish',
  'wildfly', 'websphere', 'weblogic',
  'coldfusion', 'express', 'koa',
  'fastify', 'hapi', 'sails',
  'meteor', 'feathers', 'loopback',
  'strapi', 'keystone', 'directus',
  'payload', 'sanity', 'contentful',
  'prismic', 'storyblok', 'dato cms',
  'kontent', 'builder', 'gatsby',
  'next', 'nuxt', 'remix',
  'astro', 'eleventy', 'hugo',
  'jekyll', 'hexo', 'gridsome',
  'vuepress', 'docusaurus', 'mkdocs',
  'sphinx', 'gitbook', 'bookdown',
  'rmarkdown', 'shiny', 'plumber',
  'rstudio connect', 'shiny server', 'flexdashboard',
  'blogdown', 'bookdown', 'distill',
  'xaringan', 'pagedown', 'rticles',
  'learnr', 'shinysurveys', 'shinyfeedback',
  'shinyjs', 'shinydashboard', 'shinythemes',
  'shinycssloaders', 'shinyalert', 'waiter',
  'shinybusy', 'shinycustomloader', 'shinydisconnect',
  'shinylogs', 'shinymeta', 'gargoyle',
  'shinyhelper', 'shinyWidgets', 'shinydashboardPlus',
  'shiny.semantic', 'shinybulma', 'shinyMaterial',
  'shinysky', 'shinyjqui', 'shinyTime',
  'shinyDatetimePickers', 'shinycalendar', 'shinyEffects',
  'shinyQuiz', 'shinyTutorials', 'shinyAce',
  'shinyURL', 'shinyvalidate', 'reactable',
  'DT', 'formattable', 'flextable',
  'gt', 'huxtable', 'kableExtra',
  'reactablefmtr', 'shinycssloaders', 'sortable',
  'visNetwork', 'sigmajs', 'threejs',
  'rgl', 'rayshader', 'mapdeck',
  'leaflet', 'leaflet.extras', 'leaflet.minicharts',
  'leaflet.opacity', 'leaflet.providers', 'leaflet.reveal',
  'leaflet.toolbar', 'leaflet.minicharts', 'leaflet.opacity',
  'leaflet.reveal', 'leaflet.toolbar', 'mapview',
  'tmap', 'googleway', 'googletraffic',
  'ggmap', 'plotly', 'highcharter',
  'echarts4r', 'apexcharter', 'billboarder',
  'r2d3', 'circlize', 'ComplexHeatmap',
  'corrplot', 'ggalluvial', 'ggbump',
  'ggforce', 'gghighlight', 'ggrepel',
  'ggsci', 'ggtext', 'ggtree',
  'ggwordcloud', 'gganimate', 'ggstream',
  'ggTimeSeries', 'ggthemes', 'hrbrthemes',
  'tvthemes', 'wesanderson', 'basetheme',
  'cleanthemes', 'colorblindr', 'dichromat',
  'ggthemr', 'ochRe', 'palettetown',
  'RColorBrewer', 'scico', 'viridis',
  'colorspace', 'munsell', 'farver',
  'prismatic', 'hues', 'randomcoloR',
  'rcolor', 'wesanderson', 'yarrr',
  'cartography', 'geofacet', 'geogrid',
  'rnaturalearth', 'rnaturalearthdata', 'rnaturalearthhires',
  'sf', 'sftime', 'stars',
  'sp', 'spacetime', 'spacetime',
  'spacetime', 'spatstat', 'spdep',
  'spatialreg', 'spcosa', 'sperich',
  'splancs', 'spt', 'spt',
  'spatstat', 'spatial', 'geostatistics',
  'geostat', 'gstat', 'geoR',
  'intamap', 'sdraw', 'spcosa',
  'sperich', 'spsurvey', 'spcosa',
  'sperich', 'spsurvey', 'sdraw',
  'spsurvey', 'sperich', 'spcosa',
  'sperich', 'spsurvey', 'sdraw',
  'spsurvey', 'sperich', 'spcosa'
];

const genericSites = [
  'https://www.amazon.com/s?k=kitchen+gadgets',
  'https://www.amazon.com/s?k=camping+gear',
  'https://www.amazon.com/s?k=pet+supplies',
  'https://www.ebay.com/sch/i.html?_nkw=vintage+watches',
  'https://www.target.com/s?searchTerm=home+decor',
  'https://www.walmart.com/search?q=outdoor+furniture',
  'https://www.etsy.com/search?q=handmade+jewelry',
  'https://www.bestbuy.com/site/searchpage.jsp?st=headphones',
  'https://www.homedepot.com/s/garden%20tools',
  'https://www.wayfair.com/keyword.html?keyword=rugs',
  'https://www.rei.com/search?q=hiking',
  'https://www.nordstrom.com/sr?keyword=shoes',
  'https://www.zappos.com/search?term=sneakers',
  'https://www.chewy.com/s?query=dog+toys',
  'https://www.sephora.com/search?keyword=skincare',
  'https://www.costco.com/electronics.html',
  'https://www.macys.com/shop/mens-clothing',
  'https://www.lowes.com/search?searchTerm=power+tools',
  'https://www.newegg.com/Computer-Cases/SubCategory/ID-7',
  'https://www.bhphotovideo.com/c/browse/cameras',
  'https://www.ebay.com/sch/i.html?_nkw=electronics',
  'https://www.walmart.com/search?q=electronics',
  'https://www.target.com/s?searchTerm=electronics',
  'https://www.bestbuy.com/site/electronics/abcat0100000.c?id=abcat0100000',
  'https://www.homedepot.com/b/Electrical/N-5yc1v',
  'https://www.lowes.com/cd_Electronics_706429782_',
  'https://www.ikea.com/us/en/cat/electronics/',
  'https://www.staples.com/electronics/cat_CL140405',
  'https://www.officedepot.com/c/electronics/cat/145895',
  'https://www.office.com',
  'https://www.google.com',
  'https://www.youtube.com',
  'https://www.facebook.com',
  'https://www.twitter.com',
  'https://www.instagram.com',
  'https://www.linkedin.com',
  'https://www.reddit.com',
  'https://www.wikipedia.org',
  'https://www.yahoo.com',
  'https://www.bing.com',
  'https://www.amazon.com',
  'https://www.ebay.com',
  'https://www.craigslist.org',
  'https://www.etsy.com',
  'https://www.alibaba.com',
  'https://www.aliexpress.com',
  'https://www.walmart.com',
  'https://www.target.com',
  'https://www.bestbuy.com',
  'https://www.homedepot.com',
  'https://www.lowes.com',
  'https://www.costco.com',
  'https://www.samsclub.com',
  'https://www.macys.com',
  'https://www.nordstrom.com',
  'https://www.sephora.com',
  'https://www.ulta.com',
  'https://www.cvs.com',
  'https://www.walgreens.com',
  'https://www.kroger.com',
  'https://www.safeway.com',
  'https://www.wholefoodsmarket.com',
  'https://www.traderjoes.com',
  'https://www.publix.com',
  'https://www.albertsons.com',
  'https://www.hyvee.com',
  'https://www.harristeeter.com',
  'https://www.giantfood.com',
  'https://www.weis.com',
  'https://www.gianteagle.com',
  'https://www.meijer.com',
  'https://www.wegmans.com',
  'https://www.shoprite.com',
  'https://www.acmemarkets.com',
  'https://www.pricechopper.com',
  'https://www.aldi.us',
  'https://www.lidl.com',
  'https://www.foodlion.com',
  'https://www.fredmeyer.com',
  'https://www.qfc.com',
  'https://www.citymarket.com',
  'https://www.ralphs.com',
  'https://www.food4less.com',
  'https://www.smithsfoodanddrug.com',
  'https://www.sprouts.com',
  'https://www.naturalgrocers.com',
  'https://www.wincofoods.com',
  'https://www.bjs.com',
  'https://www.safeway.com',
  'https://www.vons.com',
  'https://www.jewelosco.com',
  'https://www.shaws.com',
  'https://www.academy.com',
  'https://www.dickssportinggoods.com',
  'https://www.sportsmanswarehouse.com',
  'https://www.cabelas.com',
  'https://www.basspro.com',
  'https://www.scheels.com',
  'https://www.ganderoutdoors.com',
  'https://www.campsaver.com',
  'https://www.moosejaw.com',
  'https://www.rei.com',
  'https://www.backcountry.com',
  'https://www.eastbay.com',
  'https://www.footlocker.com',
  'https://www.finishline.com',
  'https://www.champssports.com',
  'https://www.modells.com',
  'https://www.sportinglife.com',
  'https://www.sportchalet.com',
  'https://www.sportsauthority.com',
  'https://www.6pm.com',
  'https://www.zappos.com',
  'https://www.shoes.com',
  'https://www.shoebuy.com',
  'https://www.payless.com',
  'https://www.dsw.com',
  'https://www.nordstromrack.com',
  'https://www.sierra.com',
  'https://www.landsend.com',
  'https://www.llbean.com',
  'https://www.patagonia.com',
  'https://www.columbia.com',
  'https://www.northface.com',
  'https://www.arcteryx.com',
  'https://www.marmot.com',
  'https://www.msrgear.com',
  'https://www.marmot.com',
  'https://www.keen.com',
  'https://www.teva.com',
  'https://www.chacos.com',
  'https://www.merrell.com',
  'https://www.saucony.com',
  'https://www.newbalance.com',
  'https://www.asics.com',
  'https://www.brooksrunning.com',
  'https://www.hokaoneone.com',
  'https://www.on-running.com',
  'https://www.allbirds.com',
  'https://www.vessi.com',
  'https://www.rainbowshops.com',
  'https://www.payless.com',
  'https://www.skechers.com',
  'https://www.clarksusa.com',
  'https://www.crocs.com',
  'https://www.carters.com',
  'https://www.gymboree.com',
  'https://www.childrensplace.com',
  'https://www.gap.com',
  'https://www.oldnavy.com',
  'https://www.bananarepublic.com',
  'https://www.banana-republic.gap.com',
  'https://www.athleta.gap.com',
  'https://www.piperlime.gap.com',
  'https://www.uniqlo.com',
  'https://www.hm.com',
  'https://www.zara.com',
  'https://www.forever21.com',
  'https://www.aeropostale.com',
  'https://www.americanagle.com',
  'https://www.aerie.com',
  'https://www.abercrombie.com',
  'https://www.hollisterco.com',
  'https://www.a&fco.com',
  'https://www.ae.com',
  'https://www.pacsun.com',
  'https://www.wetseal.com',
  'https://www.rue21.com',
  'https://www.fashionnova.com',
  'https://www.shein.com',
  'https://www.prettylittlething.com',
  'https://www.boohoo.com',
  'https://www.asos.com',
  'https://www.missguided.com',
  'https://www.nastygal.com',
  'https://www.urbanoutfitters.com',
  'https://www.anthropologie.com',
  'https://www.freepeople.com',
  'https://www.pacsun.com',
  'https://www.tillys.com',
  'https://www.boardies.com',
  'https://www.volley.com',
  'https://www.billabong.com',
  'https://www.quiksilver.com',
  'https://www.roxy.com',
  'https://www.hurley.com',
  'https://www.oakley.com',
  'https://www.ray-ban.com',
  'https://www.sunglasshut.com',
  'https://www.framesdirect.com',
  'https://www.coastal.com',
  'https://www.fossil.com',
  'https://www.michaelkors.com',
  'https://www.kate spade.com',
  'https://www.tory burch.com',
  'https://www.coach.com',
  'https://www.longchamp.com',
  'https://www.kipling.com',
  'https://www.skip hop.com',
  'https://www.lululemon.com',
  'https://www.under armour.com',
  'https://www.nike.com',
  'https://www.adidas.com',
  'https://www.puma.com',
  'https://www.reebok.com',
  'https://www.new balance.com',
  'https://www.converse.com',
  'https://www.vans.com',
  'https://www.volv shoes.com',
  'https://www.crocs.com',
  'https://www.birkenstock.com',
  'https://www.clarks.com',
  'https://www.dr martens.com',
  'https://www.geox.com',
  'https://www.ecco.com',
  'https://www.wolky.com',
  'https://www.gabor.com',
  'https://www.rockport.com',
  'https://www.skechers.com',
  'https://www.clarksusa.com',
  'https://www.timberland.com',
  'https://www.red wing.com',
  'https://www.hush puppies.com',
  'https://www.florsheim.com',
  'https://www.bostonian.com',
  'https://www.johnston & murphy.com',
  'https://www.allen edmonds.com',
  'https://www.cole haan.com',
  'https://www.aerosoles.com',
  'https://www.easy spirit.com',
  'https://www.naturalizer.com',
  'https://www.sam edelman.com',
  'https://www.ugg.com',
  'https://www.sorel.com',
  'https://www.columbia.com',
  'https://www.north face.com',
  'https://www.patagonia.com',
  'https://www.marmot.com',
  'https://www.mountain hardwear.com',
  'https://www.arcteryx.com',
  'https://www.salomon.com',
  'https://www.columbia sportwear.com',
  'https://www.the north face.com',
  'https://www.patagonia.com',
  'https://www.cotopaxi.com',
  'https://www.outdoor voices.com',
  'https://www.tentree.com',
  'https://www.prima loaft.com',
  'https://www.allbirds.com',
  'https://www.veja.com',
  'https://www.rivierasnekaers.com',
  'https://www.common projects.com',
  'https://www.greats.com',
  'https://www.kotn.com',
  'https://www.ministry of supply.com',
  'https://www.everlane.com',
  'https://www.patagonia.com',
  'https://www.stance.com',
  'https://www.bombas.com',
  'https://www.uniqlo.com',
  'https://www.cosstores.com',
  'https://www.mango.com',
  'https://www.mangooutlet.com',
  'https://www.massimo dutti.com',
  'https://www.pulland bear.com',
  'https://www.bershka.com',
  'https://www.stradivarius.com',
  'https://www.oysho.com',
  'https://www.zaragirls.com',
  'https://www.zarakids.com',
  'https://www.zarahome.com',
  'https://www.uenique.com',
  'https://www.teeexpress.com',
  'https://www.tee public.com',
  'https://www.red bubble.com',
  'https://www.society 6.com',
  'https://www.threadless.com',
  'https://www.design by humans.com',
  'https://www.cotton bureau.com',
  'https://www.groupon.com',
  'https://www.living social.com',
  'https://www.dealnews.com',
  'https://www.slickdeals.com',
  'https://www.retailmenot.com',
  'https://www.coupons.com',
  'https://www.valpak.com',
  'https://www.redplum.com',
  'https://www.smartsource.com',
  'https://www.couponmom.com',
  'https://www.krazycouponlady.com',
  'https://www.dealhack.com',
  'https://www.dealsplus.com',
  'https://www.couponcabin.com',
  'https://www.brads deals.com',
  'https://www.cardcash.com',
  'https://www.raise.com',
  'https://www.gift card granny.com',
  'https://www.gift card mall.com',
  'https://www.giftcards.com',
  'https://www.blackhawk network.com',
  'https://www.incomm.com',
  'https://www.galileo.com',
  'https://www.gyft.com',
  'https://www.greendot.com',
  'https://www.american express serve.com',
  'https://www.bluebird by american express.com',
  'https://www.net spend.com',
  'https://www.paypal.com',
  'https://www.venmo.com',
  'https://www.cash app.com',
  'https://www.zellepay.com',
  'https://www.apple pay.com',
  'https://www.google pay.com',
  'https://www.samsung pay.com',
  'https://www.facebook pay.com',
  'https://www.amazon pay.com',
  'https://www.paytm.com',
  'https://www.phonepe.com',
  'https://www.gpay.com',
  'https://www.bhim.com',
  'https://www.mobikwik.com',
  'https://www.freecharge.com',
  'https://www.ola money.com',
  'https://www.amazon pay.in',
  'https://www.paytm.in',
  'https://www.phonepe.in',
  'https://www.gpay.in',
  'https://www.bhim.in',
  'https://www.mobikwik.in',
  'https://www.freecharge.in',
  'https://www.ola money.in',
  'https://www.payzapp.in',
  'https://www.freecharge.in',
  'https://www.mobikwik.zinrelo.com',
  'https://www.paytm mall.com',
  'https://www.flipkart.com',
  'https://www.snapdeal.com',
  'https://www.shopclues.com',
  'https://www.infibeam.com',
  'https://www.homeshop18.com',
  'https://www.jabong.com',
  'https://www.myntra.com',
  'https://www.ajio.com',
  'https://www.limeroad.com',
  'https://www.yepme.com',
  'https://www.clovia.com',
  'https://www.zivame.com',
  'https://www.roadrunnr.in',
  'https://www.bigbasket.com',
  'https://www.grofers.com',
  'https://www.natures basket.com',
  'https://www.healthkart.com',
  'https://www.nykaa.com',
  'https://www.purplle.com',
  'https://www.beauty naap.com',
  'https://www.tata cliq.com',
  'https://www.landmarkonthenet.com',
  'https://www.futurebazaar.com',
  'https://www.industrybuying.com',
  'https://www.shopping. brand factory.com',
  'https://www.yebhi.com',
  'https://www.trade india.com',
  'https://www.indiamart.com',
  'https://www.alibaba.in',
  'https://www.made in china.com',
  'https://www.ec21.com',
  'https://www.export hub.com',
  'https://www.tradewheel.com',
  'https://www.b2b china.com',
  'https://www.dhgate.com',
  'https://www.light in the box.com',
  'https://www.tomtop.com',
  'https://www.gearbest.com',
  'https://www.dx.com',
  'https://www.banggood.com',
  'https://www.gearbest.in',
  'https://www.banggood.in',
  'https://www.aliexpress.in',
  'https://www.amazon.in',
  'https://www.flipkart.in',
  'https://www.snapdeal.in',
  'https://www.shopclues.in',
  'https://www.infibeam.in',
  'https://www.homeshop18.in',
  'https://www.jabong.in',
  'https://www.myntra.in',
  'https://www.ajio.in',
  'https://www.limeroad.in',
  'https://www.yepme.in',
  'https://www.clovia.in',
  'https://www.zivame.in',
  'https://www.roadrunnr.in',
  'https://www.bigbasket.in',
  'https://www.grofers.in',
  'https://www.natures basket.in',
  'https://www.healthkart.in',
  'https://www.nykaa.in',
  'https://www.purplle.in',
  'https://www.beauty naap.in',
  'https://www.tata cliq.in',
  'https://www.landmarkonthenet.in',
  'https://www.futurebazaar.in',
  'https://www.industrybuying.in',
  'https://www.shopping. brand factory.in',
  'https://www.yebhi.in',
  'https://www.trade india.in',
  'https://www.indiamart.in',
  'https://www.alibaba.co.in',
  'https://www.made in china.co.in',
  'https://www.ec21.co.in',
  'https://www.export hub.co.in',
  'https://www.tradewheel.co.in',
  'https://www.b2b china.co.in',
  'https://www.dhgate.co.in',
  'https://www.light in the box.co.in',
  'https://www.tomtop.co.in',
  'https://www.gearbest.co.in',
  'https://www.dx.co.in',
  'https://www.banggood.co.in',
  'https://www.gearbest.co.in',
  'https://www.banggood.co.in',
  'https://www.aliexpress.co.in'
];

// All personas available to everyone
const personas = {
  liberal_activist: {
    name: 'Liberal Activist',
    description: 'Progressive politics, climate action, social justice',
    searches: [
      'climate change protest near me', 'progressive candidates 2024',
      'renewable energy home installation', 'vegan recipes easy',
      'bernie sanders news', 'social justice books', 'blm movement updates',
      'sustainable fashion brands', 'electric car comparison',
      'planned parenthood locations', 'aclu donate', 'gun control statistics',
      'lgbtq rights news', 'minimum wage increase', 'medicare for all explained',
      'union organizing guide', 'farmers market organic', 'composting at home',
      'thrift store near me', 'fair trade coffee', 'indigenous rights movement',
      'prison reform organizations', 'voter registration deadline',
      'climate strike schedule', 'renewable energy jobs', 'community garden join',
      'biden approval rating', 'supreme court progressive', 'student debt forgiveness',
      'housing for all initiative', 'public healthcare expansion',
      'green new deal details', 'carbon tax explained', 'divestment fossil fuels',
      'reproductive rights updates', 'voting rights act amendments',
      'workers rights organizing', 'living wage campaign', 'police reform policies',
      'environmental justice communities', 'clean energy transition',
      'youth climate activism', 'racial equality movements', 'income inequality statistics',
      'affordable housing solutions', 'public education funding',
      'healthcare accessibility', 'climate migration patterns',
      'corporate accountability measures', 'democratic socialism explained',
      'progressive tax structure', 'social safety net programs',
      'labor union membership', 'worker cooperative models',
      'community organizing strategies', 'grassroots advocacy training'
    ],
    sites: [
      'https://www.nytimes.com/section/politics',
      'https://www.theguardian.com/us-news/us-politics',
      'https://www.npr.org/sections/politics/',
      'https://www.vox.com/policy-and-politics',
      'https://www.motherjones.com/',
      'https://www.huffpost.com/news/politics',
      'https://www.democracynow.org/',
      'https://www.aclu.org/',
      'https://www.patagonia.com/activism/',
      'https://www.whole-foods.com/',
      'https://www.sierraclub.org/',
      'https://www.nrdc.org/',
      'https://www.epa.gov/',
      'https://www.un.org/en/climatechange',
      'https://www.greenpeace.org/',
      'https://350.org/',
      'https://www.rainforestactiongroup.org/',
      'https://www.doctorswithoutborders.org/',
      'https://www.amnesty.org/',
      'https://www.hrw.org/'
    ]
  },

  soccer_mom: {
    name: 'Soccer Mom',
    description: 'Kids activities, family recipes, home organization',
    searches: [
      'kids soccer cleats size 4', 'healthy lunchbox ideas for kids',
      'minivan comparison 2024', 'family vacation packages',
      'homework help apps', 'kids birthday party ideas',
      'best school backpacks', 'family movie night snacks',
      'youth sports registration', 'kids tablet parental controls',
      'family meal planning app', 'carpool schedule template',
      'children vitamins gummies', 'summer camp near me',
      'kids bedroom organization', 'school supply list',
      'family game night ideas', 'kids dentist near me',
      'youth basketball leagues', 'children book recommendations',
      'potty training tips', 'kids haircut places', 'family calendar app',
      'kids water bottle spill proof', 'school fundraiser ideas',
      'after school activities', 'kids cooking classes',
      'family friendly restaurants', 'kids swimming lessons',
      'car seat safety guidelines', 'child development milestones',
      'kids craft ideas', 'budget family travel',
      'organic baby food brands', 'kids clothing size chart',
      'family health insurance', 'parenting advice toddlers',
      'kids educational apps', 'family fitness activities',
      'homemade baby food', 'kids allergy symptoms',
      'family budget planner', 'kids orthodontist near me',
      'childrens museum events', 'family vacation rentals',
      'kids winter coats', 'car seat installation',
      'baby sleep training', 'kids sports physical',
      'family photo session', 'childrens dentist',
      'kids vitamins d', 'family therapy near me',
      'parent teacher conference tips', 'kids first aid kit',
      'family camping gear', 'kids bike helmet size',
      'childrens ibuprofen dosage', 'family emergency plan'
    ],
    sites: [
      'https://www.target.com/c/kids/-/N-5xtly',
      'https://www.amazon.com/s?k=kids+toys',
      'https://www.pinterest.com/ideas/family/',
      'https://www.allrecipes.com/recipes/1947/everyday-cooking/family-dinners/',
      'https://www.parents.com/',
      'https://www.walmart.com/cp/kids-clothing/5438',
      'https://www.carters.com/',
      'https://www.containerstore.com/welcome.htm',
      'https://www.costco.com/grocery.html',
      'https://www.samsclub.com/',
      'https://www.kidsbowlfree.com/',
      'https://www.imom.com/',
      'https://www.babycenter.com/',
      'https://www.whattoexpect.com/',
      'https://www.verywellfamily.com/',
      'https://www.familyhandyman.com/',
      'https://www.activityvillage.co.uk/',
      'https://www.nickjr.com/',
      'https://www.sesamestreet.org/',
      'https://www.pbskids.org/'
    ]
  },

  college_girl: {
    name: 'College Girl',
    description: 'Horoscopes, beauty trends, social media, dating',
    searches: [
      'mercury retrograde dates 2024', 'zodiac compatibility calculator',
      'horoscope today gemini', 'tarot reading online free',
      'dorm room decor ideas', 'best mascara drugstore',
      'hinge profile tips', 'apartment decorating cheap',
      'study playlist spotify', 'iced coffee recipe', 'thrift haul ideas',
      'manifestation journal prompts', 'skincare routine oily skin',
      'part time jobs college students', 'cheap date ideas',
      'taylor swift concert tickets', 'trendy outfits pinterest',
      'student discount codes', 'anxiety tips college',
      'roommate agreement template', 'finals week survival tips',
      'budgeting app students', 'crystals for beginners',
      'friendship bracelet patterns', 'aesthetic room makeover',
      'sagittarius horoscope weekly', 'aquarius love compatibility',
      'leo career horoscope', 'aries daily horoscope',
      'aries weekly tarot reading', 'cancer moon sign meaning',
      'capricorn rising traits', 'scorpio soulmate signs',
      'virgo self love affirmations', 'pisces spiritual awakening',
      'libra relationship advice', 'taurus money horoscope',
      'gemini communication tips', 'trending tiktok dances',
      'insta story ideas', 'vsco girl aesthetic outfits',
      'thrift flip ideas', 'frugal college student tips',
      'college party outfit', 'dorm room essentials',
      'back to school haul', 'gen z slang words',
      'tiktok makeup tutorial', 'youtube study playlist',
      'netflix shows 2024', 'spotify college playlist',
      'amazon college must haves', 'target dorm room',
      'urban outfitters sale', 'aeo student discount',
      'hollister college style', 'forever 21 haul',
      'shein haul review', 'romwe outfit ideas',
      'fashion nova reviews', 'boohoo student discount'
    ],
    sites: [
      'https://www.cosmopolitan.com/',
      'https://www.refinery29.com/',
      'https://www.bustle.com/',
      'https://www.astrology.com/horoscope/daily.html',
      'https://www.sephora.com/shop/bestsellers',
      'https://www.ulta.com/skin-care',
      'https://www.shein.com/',
      'https://www.pinterest.com/ideas/aesthetic/',
      'https://www.spotify.com/',
      'https://www.tiktok.com/',
      'https://www.instagram.com/',
      'https://www.youtube.com/',
      'https://www.urbanoutfitters.com/',
      'https://www.ae.com/',
      'https://www.hollisterco.com/',
      'https://www.forever21.com/',
      'https://www.nordstrom.com/',
      'https://www.missguided.com/',
      'https://www.prettylittlething.com/',
      'https://www.boohoo.com/'
    ]
  },

  tech_bro: {
    name: 'Tech Bro',
    description: 'Crypto, startups, gadgets, hustle culture',
    searches: [
      'bitcoin price prediction', 'best crypto wallet 2024',
      'startup funding rounds', 'y combinator application tips',
      'tesla stock analysis', 'elon musk twitter', 'ai tools productivity',
      'mechanical keyboard build guide', 'standing desk setup',
      'soylent alternative', 'nootropics for focus', 'cold plunge benefits',
      'venture capital trends', 'saas metrics dashboard',
      'remote work tools', 'productivity hacks morning routine',
      'tech layoffs news', 'silicon valley networking events',
      'coding bootcamp worth it', 'side hustle ideas tech',
      'angel investing beginners', 'web3 explained', 'chatgpt prompts',
      'monitor ultrawide setup', 'espresso machine office',
      'ethereum merge update', 'solana network status',
      'nft marketplace trends', 'defi yield farming',
      'metaverse real estate', 'blockchain gaming',
      'ai image generator', 'machine learning courses',
      'cloud computing aws', 'kubernetes tutorial',
      'docker container setup', 'github actions ci cd',
      'python data science', 'javascript framework comparison',
      'react vs vue', 'nextjs tutorial',
      'nodejs performance', 'database optimization',
      'api design best practices', 'microservices architecture',
      'devops tools 2024', 'cybersecurity trends',
      'artificial intelligence news', 'quantum computing explained',
      'iot devices security', '5g network rollout',
      'edge computing benefits', 'serverless architecture',
      'progressive web apps', 'mobile app development',
      'ux design principles', 'agile methodology',
      'scrum master certification', 'project management tools',
      'remote team building', 'virtual collaboration',
      'digital nomad setup', 'coworking spaces',
      'freelance tech jobs', 'contract developer rates'
    ],
    sites: [
      'https://news.ycombinator.com/',
      'https://www.theverge.com/',
      'https://techcrunch.com/',
      'https://www.wired.com/',
      'https://www.coinbase.com/',
      'https://www.producthunt.com/',
      'https://www.tesla.com/',
      'https://www.newegg.com/',
      'https://github.com/trending',
      'https://www.reddit.com/r/technology/',
      'https://www.stackoverflow.com/',
      'https://www.medium.com/',
      'https://www.dev.to/',
      'https://www.freecodecamp.org/',
      'https://www.hackerrank.com/',
      'https://www.leetcode.com/',
      'https://www.angellist.com/',
      'https://www.crunchbase.com/',
      'https://www.pitchbook.com/',
      'https://www.linkedin.com/'
    ]
  },

  fitness_influencer: {
    name: 'Fitness Influencer',
    description: 'Gym workouts, supplements, athleisure, wellness',
    searches: [
      'best pre workout 2024', 'protein powder comparison',
      'leg day workout routine', 'macro calculator bodybuilding',
      'gym outfit ideas', 'fitness transformation tips',
      'creatine loading phase', 'home gym equipment essentials',
      'meal prep bodybuilding', 'bcaa vs eaa', 'lululemon sale',
      'gymshark new arrivals', 'whey isolate vs concentrate',
      'shoulder workout exercises', 'bulk or cut calculator',
      'fitness influencer tips', 'gym mirror selfie lighting',
      'post workout smoothie recipe', 'rest day activities',
      'foam rolling routine', 'deadlift form check', 'ab workout 10 min',
      'collagen peptides benefits', 'sleep supplement melatonin',
      'hydration tracker app', 'crossfit wod today',
      'olympic lifting technique', 'powerlifting program',
      'bodyweight exercises list', 'hiit workout routine',
      'cardio for fat loss', 'strength training beginner',
      'kettlebell workout plan', 'yoga for flexibility',
      'pilates core exercises', 'stretching for runners',
      'recovery methods athletes', 'injury prevention tips',
      'sports nutrition guide', 'electrolyte replacement',
      'branched chain amino acids', 'glutamine benefits',
      'beta alanine side effects', 'caffeine pre workout',
      'natural testosterone boosters', 'fat burner supplements',
      'prebiotics probiotics', 'adaptogenic herbs',
      'anti inflammatory foods', 'keto diet for athletes',
      'intermittent fasting results', 'cycling for cardio',
      'swimming workout plan', 'calisthenics progression',
      'resistance band exercises', 'trx suspension training',
      'battle ropes workout', 'sled pushes benefits',
      'sprint interval training', 'tabata workout timer',
      'emom workout examples', 'amrap workout ideas',
      'emom meaning fitness', 'wod meaning crossfit'
    ],
    sites: [
      'https://www.bodybuilding.com/',
      'https://www.myfitnesspal.com/',
      'https://www.gymshark.com/',
      'https://shop.lululemon.com/',
      'https://www.gnc.com/',
      'https://www.muscleandstrength.com/',
      'https://www.nike.com/w/training-shoes-58jtoz7ldp5',
      'https://www.amazon.com/s?k=fitness+equipment',
      'https://www.instagram.com/',
      'https://www.youtube.com/results?search_query=workout',
      'https://www.t-nation.com/',
      'https://www.muscleandfitness.com/',
      'https://www.shape.com/',
      'https://www.menshealth.com/',
      'https://www.womenshealthmag.com/',
      'https://www.health.com/',
      'https://www.precisionnutrition.com/',
      'https://www.nerdfitness.com/',
      'https://www.musclewiki.com/',
      'https://www.fitbit.com/'
    ]
  },

  boomer_dad: {
    name: 'Boomer Dad',
    description: 'Golf, grilling, home improvement, classic rock',
    searches: [
      'golf clubs for beginners', 'weber grill accessories',
      'lawn care schedule', 'best riding mower 2024',
      'classic rock concerts near me', 'nfl scores today',
      'home depot tool sale', 'garage organization ideas',
      'fishing gear bass', 'retirement calculator',
      'best bourbon under 50', 'recliner chair leather',
      '401k withdrawal rules', 'blood pressure monitor',
      'golf swing tips', 'steak grilling temperature',
      'led zeppelin vinyl', 'truck comparison 2024',
      'fantasy football rankings', 'driveway sealer best',
      'wood deck stain', 'bird feeder squirrel proof',
      'medicare supplement plans', 'social security calculator',
      'prostate health supplements', 'grill master tips',
      'john deere tractor parts', 'home workshop setup',
      'tool storage solutions', 'diy home repair',
      'electrical wiring basics', 'plumbing repair guide',
      'hvac maintenance schedule', 'roofing materials cost',
      'concrete patio ideas', 'landscaping design',
      'garden shed storage', 'pressure washer reviews',
      'chainsaw safety tips', 'outdoor lighting ideas',
      'patio furniture sets', 'fire pit designs',
      'bbq rub recipes', 'smoker meat temperatures',
      'classic car restoration', 'motorcycle maintenance',
      'boat motor repair', 'rv travel destinations',
      'camping gear essentials', 'hiking trail maps',
      'fishing lure selection', 'hunting rifle scope',
      'deer stand locations', 'waterfowl hunting',
      'turkey call techniques', 'fishing knot tying',
      'bass fishing techniques', 'fly fishing setup',
      'ice fishing gear', 'surf fishing tips',
      'saltwater fishing', 'freshwater fishing'
    ],
    sites: [
      'https://www.homedepot.com/',
      'https://www.lowes.com/',
      'https://www.espn.com/',
      'https://www.golfdigest.com/',
      'https://www.weber.com/',
      'https://www.dickssportinggoods.com/',
      'https://www.cabelas.com/',
      'https://www.ford.com/trucks/',
      'https://www.aarp.org/',
      'https://www.foxnews.com/',
      'https://www.cbsnews.com/',
      'https://www.nbcnews.com/',
      'https://www.abcnews.go.com/',
      'https://www.bbc.com/news',
      'https://www.realtor.com/',
      'https://www.zillow.com/',
      'https://www.trulia.com/',
      'https://www.remax.com/',
      'https://www.kbb.com/',
      'https://www.edmunds.com/'
    ]
  },

  conspiracy_theorist: {
    name: 'Conspiracy Theorist',
    description: 'Alternative news, supplements, prepping, truth seeking',
    searches: [
      'government surveillance protection', 'vpn best privacy',
      'water filter fluoride removal', 'survival food storage',
      'solar generator emergency', 'faraday cage diy',
      'alternative news sources', 'gold investment ira',
      'ham radio license', 'off grid living guide',
      'seed vault buy', 'emergency preparedness kit',
      'natural remedies immune system', 'detox heavy metals',
      'cash vs digital currency', 'land for sale rural',
      'second passport how to', 'bunker construction cost',
      'night vision binoculars', 'encrypted messaging apps',
      'home security camera offline', 'medical supplies stockpile',
      'generator whole house', 'well drilling cost',
      'property tax free states', 'constellation disclosure',
      'chemtrail effects health', '5g health risks',
      'covid vaccine ingredients', 'microchip tracking',
      'new world order signs', 'agenda 21 explained',
      'georgia guidestones meaning', 'reptilian elite',
      'alien disclosure program', 'underground bases',
      'hollow earth theory', 'flat earth proof',
      'nibiru planet x', 'comet catalysts',
      'false flag operations', 'operation mockinbird',
      'cfr membership list', 'bilderberg group agenda',
      'trilateral commission', 'club of rome',
      'rothschild family net worth', 'federal reserve owners',
      'quantum timeline healing', 'ascension symptoms',
      'law of attraction', 'crystal healing properties',
      'chakra balancing guide', 'essential oils benefits',
      'activated charcoal uses', 'iodine deficiency symptoms',
      'colloidal silver health', 'ozone therapy benefits',
      'herbal antibiotic alternatives', 'natural cancer cures',
      'cancer cluster causes', 'gmo health effects',
      'chemo alternatives', 'radiation detox',
      'electromagnetic hypersensitivity', 'smart meter dangers'
    ],
    sites: [
      'https://www.infowars.com/',
      'https://www.zerohedge.com/',
      'https://www.naturalnews.com/',
      'https://www.survivalblog.com/',
      'https://www.goldsilver.com/',
      'https://www.augasonfarms.com/',
      'https://www.rei.com/c/emergency-supplies',
      'https://www.amazon.com/s?k=survival+gear',
      'https://www.duckduckgo.com/',
      'https://www.protonmail.com/',
      'https://www.privacytools.io/',
      'https://www.torproject.org/',
      'https://www.bitchute.com/',
      'https://www.rumble.com/',
      'https://www.gab.com/',
      'https://www.minds.com/',
      'https://www.steemit.com/',
      'https://www.publish0x.com/',
      'https://www.medium.com/',
      'https://www.substack.com/'
    ]
  },

  luxury_shopper: {
    name: 'Luxury Shopper',
    description: 'Designer brands, fine dining, travel, wealth',
    searches: [
      'louis vuitton new collection', 'chanel bag classic flap',
      'rolex authorized dealer', 'first class flights deals',
      'michelin star restaurants', 'luxury hotel suites',
      'private jet charter cost', 'yacht rental mediterranean',
      'hermes birkin waitlist', 'gucci loafers men',
      'wine collection storage', 'art investment guide',
      'wealth management firms', 'country club membership',
      'personal shopper service', 'luxury real estate',
      'ferrari dealership', 'private chef hire',
      'golf resort vacation', 'spa retreat wellness',
      'diamond engagement ring', 'bespoke suit tailor',
      'interior designer luxury', 'personal assistant services',
      'concierge medicine doctors', 'private island for sale',
      'supercar rental', 'helicopter tour las vegas',
      'luxury cruise lines', 'designer handbag auction',
      'fine jewelry brands', 'luxury watch brands',
      'designer clothing sales', 'luxury car brands',
      'private equity investing', 'hedge fund performance',
      'real estate investment', 'art gallery new york',
      'sothebys auction results', 'christies art auction',
      'private art collection', 'wine auction results',
      'luxury fashion weeks', 'paris runway shows',
      'milan fashion week', 'london fashion week',
      'new york fashion week', 'luxury resort destinations',
      'private beach clubs', 'exclusive golf courses',
      'luxury ski resorts', 'private villa rentals',
      'fine dining restaurants', 'michelin star chefs',
      'sommelier services', 'caviar delivery service',
      'luxury yacht brokers', 'private jet brokers',
      'helicopter charter service', 'luxury car auctions',
      'supercar manufacturers', 'bespoke car customization',
      'luxury home architects', 'interior design firms',
      'landscape architects', 'luxury home builders'
    ],
    sites: [
      'https://www.louisvuitton.com/',
      'https://www.chanel.com/',
      'www.gucci.com/',
      'https://www.rolex.com/',
      'https://www.netaporter.com/',
      'https://www.mrporter.com/',
      'https://www.farfetch.com/',
      'https://www.sothebys.com/',
      'https://www.christies.com/',
      'https://www.fourseasons.com/',
      'https://www.ritzcarlton.com/',
      'https://www.bulgari.com/',
      'https://www.tiffany.com/',
      'https://www.cartier.com/',
      'https://www.hermes.com/',
      'https://www.prada.com/',
      'https://www.balenciaga.com/',
      'https://www.dior.com/',
      'https://www.yves-saint-laurent.com/',
      'https://www.bottegaveneta.com/'
    ]
  }
};

// Get search terms based on persona (or generic if none selected)
function getSearchTerms(persona) {
  const terms = personas[persona]?.searches ?? genericSearchTerms;
  // Apply random typos to some terms (5% chance)
  return terms.map(term => Math.random() < 0.05 ? introduceTypo(term) : term);
}

// Get sites based on persona (or generic if none selected)
function getSites(persona) {
  return personas[persona]?.sites ?? genericSites;
}

// Get delay based on frequency setting
function getDelay(frequency) {
  const { minDelay, maxDelay } = frequencies[frequency] ?? frequencies.medium;
  return Math.floor(Math.random() * (maxDelay - minDelay)) + minDelay;
}

// Simple typo introduction function
function introduceTypo(text) {
  // Common typo patterns:
  // 1. Letter substitution (swapping adjacent letters)
  // 2. Missing letters
  // 3. Extra letters
  // 4. Wrong letters (nearby on keyboard)

  if (text.length < 3) return text; // Don't typo very short terms

  const typoType = Math.floor(Math.random() * 4);
  const index = Math.floor(Math.random() * (text.length - 1)) + 1; // Avoid first char

  switch (typoType) {
    case 0: // Letter substitution (swap adjacent)
      if (index < text.length - 1) {
        const chars = text.split('');
        [chars[index], chars[index + 1]] = [chars[index + 1], chars[index]];
        return chars.join('');
      }
      return text;

    case 1: // Missing letter
      return text.substring(0, index) + text.substring(index + 1);

    case 2: // Extra letter (duplicate)
      return text.substring(0, index) + text.charAt(index) + text.substring(index);

    case 3: // Wrong letter (nearby on QWERTY keyboard)
      const nearbyKeys = {
        'a': ['q', 'w', 's', 'z'],
        'b': ['v', 'g', 'h', 'n'],
        'c': ['x', 'd', 'f', 'v'],
        'd': ['s', 'e', 'r', 'f', 'c', 'x'],
        'e': ['w', '3', '4', 'r', 'd', 's'],
        'f': ['d', 'r', 't', 'g', 'v', 'c'],
        'g': ['f', 't', 'y', 'h', 'b', 'v'],
        'h': ['g', 'y', 'u', 'j', 'n', 'b'],
        'i': ['u', '8', '9', 'o', 'k', 'j'],
        'j': ['h', 'u', 'i', 'k', 'm', 'n'],
        'k': ['j', 'i', 'o', 'l', 'm'],
        'l': ['k', 'o', 'p'],
        'm': ['n', 'j', 'k'],
        'n': ['b', 'h', 'j', 'm'],
        'o': ['i', '9', '0', 'p', 'l', 'k'],
        'p': ['o', '0', 'l'],
        'q': ['1', '2', 'w', 'a'],
        'r': ['e', '4', '5', 't', 'f', 'd'],
        's': ['a', 'w', 'e', 'd', 'x', 'z'],
        't': ['r', '5', '6', 'y', 'g', 'f'],
        'u': ['y', '7', '8', 'i', 'j', 'h'],
        'v': ['c', 'f', 'g', 'b'],
        'w': ['q', '2', '3', 'e', 's', 'a'],
        'x': ['z', 's', 'd', 'c'],
        'y': ['t', '6', '7', 'u', 'h', 'g'],
        'z': ['a', 's', 'x']
      };

      const char = text.charAt(index).toLowerCase();
      if (nearbyKeys[char]) {
        const replacement = nearbyKeys[char][Math.floor(Math.random() * nearbyKeys[char].length)];
        return text.substring(0, index) + replacement + text.substring(index + 1);
      }
      return text;
  }

  return text;
}

// Get all personas for UI
function getPersonaList() {
  return Object.entries(personas).map(([id, data]) => ({
    id,
    name: data.name,
    description: data.description
  }));
}

// Get frequency options for UI
function getFrequencyList() {
  return Object.entries(frequencies).map(([id, data]) => ({
    id,
    name: data.name,
    label: data.label,
    description: data.description,
    warning: data.warning
  }));
}

module.exports = {
  frequencies,
  personas,
  genericSearchTerms,
  genericSites,
  getSearchTerms,
  getSites,
  getDelay,
  getPersonaList,
  getFrequencyList
};
